/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package allpanels;

import com.mycompany.medicalshop.DataBaseConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RITIK
 */
public class AddProduct extends javax.swing.JPanel {

    /**
     * Creates new form AddProduct
     */
    int user_id;

    public AddProduct() {
        initComponents();
    }

    public AddProduct(int user) {
        initComponents();
        user_id = user;
        getProduct("all");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnum = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qua = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pcombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchproduct = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Product number");

        pnum.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        pnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnumMouseClicked(evt);
            }
        });
        pnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnumActionPerformed(evt);
            }
        });

        pname.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        pname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnameFocusLost(evt);
            }
        });
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Product name");

        jLabel3.setText("Product price");

        pprice.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        pprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Sale price");

        sprice.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        sprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Manufacturing date");

        mdate.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        mdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Expiry date");

        edate.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        edate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Quantity");

        qua.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        qua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaActionPerformed(evt);
            }
        });

        jButton1.setText("ADD NEW PRODUCT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select type", "kg", "liter" }));
        pcombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnum)
                    .addComponent(pname)
                    .addComponent(pprice)
                    .addComponent(sprice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mdate)
                    .addComponent(edate)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(pcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pprice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, 540));

        product_table.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(product_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 590, 450));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD NEW PRODUCT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(702, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 40));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADD PRODUCT LIST");

        searchproduct.setText("search product");
        searchproduct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchproductFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchproductFocusLost(evt);
            }
        });
        searchproduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchproductKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(searchproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(searchproduct)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 610, 40));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void getProduct(String data1) {
        try {
            Connection con = DataBaseConnection.getConnection();

            String qry = "";

            if (data1.equals("all")) {
                qry = "SELECT * FROM addproduct WHERE user_id='" + user_id + "'";
            } else {
                qry = "SELECT * FROM addproduct WHERE user_id='" + user_id + "' and product_name LIKE '%" + data1 + "%'";
            }
            PreparedStatement preparedStatement = con.prepareStatement(qry);
            ResultSet resultSet = preparedStatement.executeQuery();

            String field_name[] = {"Porduct Number", "Product_name", "Expiring", "Quantity", "Sale Price"};

            DefaultTableModel defaultTableModel = new DefaultTableModel(field_name, 0);

            while (resultSet.next()) {
                String p_num = resultSet.getString("product_number");
                String p_name = resultSet.getString("product_name");
                String p_price = resultSet.getString("product_price");
                String p_exp = resultSet.getString("Expiring");
                String p_qnt = resultSet.getString("quantity");

                String[] data = {p_num, p_name, p_exp, p_qnt, p_price};
                defaultTableModel.addRow(data);
            }
            product_table.setModel(defaultTableModel);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "DATABASE Product ERRO");
            System.out.println("Product ERRO =>" + e);
        }

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            String num = pnum.getText();
            String name = pname.getText();
            String pr = pprice.getText();
            String sp = sprice.getText();
            String mf = mdate.getText();
            String exp = edate.getText();
            String q = qua.getText();
            String qt = (String) pcombo.getSelectedItem();
            if (num.equals(" ") || name.equals(" ") || pr.equals(" ") || sp.equals(" ") || q.equals(" ") || qt.equals(" ")) {
                if (num.equals("")) {
                    pnum.setBackground(Color.red);
                } else {
                    pnum.setBackground(Color.white);
                }
                if (name.equals("")) {
                    pname.setBackground(Color.red);
                } else {
                    pname.setBackground(Color.white);
                }
                if (pr.equals("")) {
                    pprice.setBackground(Color.red);
                } else {
                    pprice.setBackground(Color.white);
                }
                if (sp.equals("")) {
                    sprice.setBackground(Color.red);
                } else {
                    sprice.setBackground(Color.white);
                }

                if (q.equals("")) {
                    qua.setBackground(Color.red);
                } else {
                    qua.setBackground(Color.white);
                }
            } else {
                JOptionPane.showMessageDialog(this, "AddProduct=>" + user_id);
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/medicaldatabase", "root", "");
                String qry = "INSERT into addproduct(product_number,product_name,product_price,sale_price,Manufacturing,Expiring,quantity,quantity_type,user_id)values(?,?,?,?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(qry);
                ps.setString(1, num);
                ps.setString(2, name);
                ps.setString(3, pr);
                ps.setString(4, sp);
                ps.setString(5, mf);
                ps.setString(6, exp);
                ps.setString(7, q);
                ps.setString(8, qt);
                ps.setInt(9, user_id);
                int i = ps.executeUpdate();
                if (i == 1) {
                    System.out.println("new product add");
                    JOptionPane.showMessageDialog(this, "new product add");
                    cleatText();
                    getProduct("all");
                } else {
                    System.out.println("new productis not add");
                    JOptionPane.showMessageDialog(this, "new product is not add");
                }
            }
        } catch (Exception e) {
            System.out.println("error=" + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void cleatText() {
        pname.setText("");
        pnum.setText("");
        sprice.setText("");
        pprice.setText("");
        edate.setText("");
        mdate.setText("");
        qua.setText("");
    }

    private void quaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quaActionPerformed

    private void pnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnumActionPerformed
        // TODO add your handling code here:

        Random r = new Random();
        int r_num = r.nextInt(9 * 9);
        String product_name = pname.getText();
        String data = product_name.substring(0, 3) + r_num;
        pnum.setText(data);
    }//GEN-LAST:event_pnumActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void pcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcomboActionPerformed

    private void pnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnameFocusLost
        Random r = new Random();
        int r_num = r.nextInt(9 * 99);
        String product_name = pname.getText();
        String data = product_name.substring(0, 3) + r_num;
        pnum.setText(data);
    }//GEN-LAST:event_pnameFocusLost

    private void searchproductFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchproductFocusGained
        searchproduct.setText("");
    }//GEN-LAST:event_searchproductFocusGained

    private void searchproductFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchproductFocusLost
        String k = searchproduct.getText();
        if (k.equals("")) {
            searchproduct.setText("Search Product");

        }
    }//GEN-LAST:event_searchproductFocusLost

    private void searchproductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchproductKeyReleased
        String data = searchproduct.getText();
        if (!data.equals("")) {
            getProduct(data);
        } else {
            getProduct("all");
        }
    }//GEN-LAST:event_searchproductKeyReleased

    private void pnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnumMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "product number is automatically generate please don't fill it");
    }//GEN-LAST:event_pnumMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mdate;
    private javax.swing.JComboBox<String> pcombo;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pnum;
    private javax.swing.JTextField pprice;
    private javax.swing.JTable product_table;
    private javax.swing.JTextField qua;
    private javax.swing.JTextField searchproduct;
    private javax.swing.JTextField sprice;
    // End of variables declaration//GEN-END:variables

    private void getProduct() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
